export const routes = {
    Home: "/",
    Search: "/search",
    SearchDetail: "/search/detail",
    RestaurantDetail: "/restaurant",
    SignIn: "/login",
    Otp: "/phone_verification",
    AdditionalSignUpInfo: "/additional",
    RegistrationSuccess: "/registration_success",
    ProductDetail: "/detail",
    ConfirmOrder: "/confirm",
    review: "/review",
    OrderDetail: "/order/detail",
    OrderHistory: "/order/history",
    Profile: "/profile",
};
