name: CICD with EC2

on:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-22.04

        if: github.ref == 'refs/heads/main'

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"

            - run: yarn install --immutable
            - run: yarn build

            - name: rsync deployments
              uses: burnett01/rsync-deployments@6.0.0
              with:
                  switches: -avzr --delete --include=".next"
                  path: ./*
                  remote_path: /var/www/web-customer/
                  remote_host: 13.214.73.95
                  remote_user: ubuntu
                  remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
